version: '3'

volumes:
  pg_data:
  # static_value:
  static:
  media_value:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    # image: fxflorian/kittygram_backend
    image: fxflorian/foodgram_backend
    env_file: .env
    volumes:
      # - static_value:/app/static/
      # - static:/static
      - static:/static_backend
      - media_value:/app/media/

  frontend:
    # image: fxflorian/kittygram_frontend  # Качаем с DockerHub
    image: fxflorian/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      # - ../frontend/:/app/result_build/
      - static:/static

  nginx:
    # image: fxflorian/kittygram_gateway  # Качаем с DockerHub
    image: fxflorian/foodgram_nginx
    env_file: .env
    ports:
      - 9000:80
    volumes:
      # - static_value:/var/html/static/
      - static:/static
      - media_value:/var/html/media/

