version: '3'

volumes:
  static:
  media_value:
  pg_data:

services:

  db:
    image: postgres:13.0-alpine
    container_name: db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      #- db_data:/var/lib/postgresql/data/
    restart: always

  backend:
    container_name: foodgram_backend
    build: backend
    restart: always
    volumes:
      - static:/static_backend
      - media_value:/app/media/
    depends_on:
      - db
    env_file: .env

  frontend:
    container_name: foodgram_frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
      
  nginx:
    image: nginx:1.19.3
    ports:
      - 9000:80
      # - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media_value:/var/html/media/
    depends_on:
      - backend
    restart: always
