version: '3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    container_name: foodgram_backend
    build: ../backend/ # Из какого Dockerfile собирать образ для этого контейнера:
    # image: fxflorian/foodgram_backend:latest # Из какого образа запустить контейнер:
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    container_name: foodgram_frontend
    # image: fxflorian/foodgram_frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

      
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
      # - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes: 
  static_value:
  media_value:
  pg_data: